noinst_PROGRAMS += json-to-bson
json_to_bson_SOURCES = $(top_srcdir)/examples/json-to-bson.c
json_to_bson_CPPFLAGS = -I$(top_srcdir)/j2bson `pkg-config --cflags libbson-1.0`
json_to_bson_LDADD = libj2bson-1.0.la
json_to_bson_LDFLAGS = `pkg-config --libs libbson-1.0` -lyajl
